# Generated by Django 4.1.1 on 2022-10-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_datecomplete_task_datecompleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
