# Generated by Django 4.1.1 on 2022-10-19 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
